### ISSUE TITLE
CSS tweaks to share

### ISSUE THREAD

**Issue by oliverh72** [fguillot/kanboard#1248]
I tweaked the CSS using Stylish a bit. You can do the same or add it as a supplementary CSS include.

I've focused on adding a bit more space and larger fonts pretty much throughout. I tried to clarify the headings from the content a bit. I've rounded the cards and made recent cards have a bottom border instead of the slightly-too-subtle drop shadow. Tweak as you prefer.

Thanks for the great app!

div.task-board-recent { box-shadow: none; border-bottom: 6px solid rgba(0, 0, 0, 0.3); }
div.ganttview-vtheader-series-name { padding: 0 6px; }
th, td { padding: 10px; }
header { border-bottom: none; }
label { font-weight: bold; margin-top: 18px; }
.task-board { margin-bottom: 8px; padding: 12px; border-radius: 6px; }
.task-board-title { font-size: 1.25em; font-weight: 600; }
.task-show-details { border-radius: 10px; margin-bottom: 20px; }
.task-show-details h2 { background-color: rgba(0, 0, 0, 0.3); padding: 20px; border-radius: 8px 8px 0 0; color: #fff; }
.task-show-details ul { padding: 20px; }
.table-small { font-size: 1em; }
.sidebar { background-color: #f7f7f7; }
.sidebar ul { padding-bottom: 20px; border-bottom: 1px solid #ddd; }
.sidebar ul:last-of-type { border-bottom: none; }
.sidebar-collapse i, .sidebar-collapsed .sidebar { background-color: #999; border-radius: 24px; padding: 5px 10px 5px 8px; }
.sidebar-collapse i, .sidebar-collapsed .sidebar i { color: #fff; }
.sidebar-collapse i:hover, .sidebar-collapsed .sidebar:hover { background-color: #ccc; }
.page-header { margin: 15px 0; background-color: #eee; padding: 6px 10px 10px 10px; border-bottom: 1px solid #ddd; border-top: 1px solid #ddd; }
.page-header li { font-size: 1.1em; }
.page-header h2 { border-bottom: none; }
.listing { border: none; }
.fa-play { font-size: 1.2em; background-color: #ddd; border-radius: 100%; width: 25px; height: 28px; padding: 8px 0 0 15px; margin-right: 8px; }
.fa-play:hover { background-color: #090; color: #fff; }
.fc-event .fc-content { padding: 4px 8px; }
.board-add-icon { padding: 0; margin-right: 12px; }
.board-add-icon a { color: #090; padding: 0px 6px 3px 6px; margin-bottom: -4px; }
.board-add-icon a:hover { border-radius: 100%; background-color: #090; color: #fff; }
.form-column select { font-size: 1.2em; margin: 10px 0 2px 0; }
.form-column:nth-of-type(2) { padding: 10px 25px; background-color: #f7f7f7; }
.form-actions { font-size: 1.2em; }
.page-header ul.dropdown-submenu-open { margin: 10px 0 0 -10px; padding: 0; }
.dropdown-submenu-open li:nth-child(even) { background-color: #f7f7f7; }
.dropdown-submenu-open li { padding: 6px 10px; }
.dropdown-submenu-open li:hover { background-color: #eee; }
.filters { border: none; }
.filters ul.dropdown-submenu-open { margin: 6px 0 0 8px; }

**Comment by walter03** [comment]
great, thanks! How did you integrate it? When I try to copy&past into the app-settings customer CSS field, I get an error - maybe it contains conflicting SQL keywords or the size of the text is too long...

**Comment by BlueTeck** [comment]
Seems to work with sqlite, but not with mysql.

**Comment by fguillot** [comment]
With Mysql the field is limited to 255 characters. If you need more than that, you are better to use a plugin (available only with the development version).

I added an example of plugin to add a new stylesheet: https://github.com/kanboard/plugin-example-css

Basically, it's just a plugin with only one line of code, very easy.

**Comment by oliverh72** [comment]
I'm just using Stylish in Chrome (also available in FF) which allows you inject CSS into any site, on a per-site basis. But the plugin is even better - I was going to customize kanboard add it as a custom stylesheet once I was ready to make it permanent. Thanks!

**Comment by thob** [comment]
:+1:

**Comment by phillc73** [comment]
Inspired initially by wanting to change the background colour of board cards to white, and the answers [here](https://github.com/fguillot/kanboard/issues/404), I've made quite a few changes to the layout, Happy to share. All changes made under Settings/Application Settings/Customer Stylesheet, rather than with the beta plugin option. I didn't use anything special like Stylish, just wrote things out by hand after finding the relevant elements using the inspector.

My changes essentially do the following:

1. Solid colour header, full width of page, no margins. In the example CSS below, my header is green.

2. Main page content with 20 pixel margins left and right.

3. All links black, rather than blue. Change to grey with mouseover. No underlines. (Although the bold links for each section, e.g. Application Settings, do still have an underline as I haven't quite figured out which tag to alter for this yet.

4. Board cards for many colours now have a white background. Yellow, blue, green, purple, orange, red, grey included.

5. Board cards still have a coloured margin. Those for green, blue, red, purple and orange have been altered to deeper solid colours.

6. Board columns have a grey background and the cards are tweaked to slightly have a top and right margin to show drop shadow.

7. Changed the main project name in the header to white text (still should probably alter the logout text on the right to match). I'd also quite like to alter the KB logo to a Home icon at some point. The grey/red combination doesn't go too well with the darker background header.

I need to convince a team to switch from ToDoist and Trello to Kanboard, so wanted to enhance the design a little.

```CSS
header {
    background-color: rgb(0, 153, 76);
    padding: 10px 10px 15px 10px;
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 0px;
}

h1 {
    font-weight: normal;
    color: #FFFFFF;
}

body {
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 0px;
    padding-bottom: 0px;
    padding-top: 0px;
    color: #333;
    font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif;
    text-rendering: optimizeLegibility;
}

.page {
    margin-left: 20px;
    margin-right: 20px;
    clear: both;
}

.ui-sortable {
    background-color: rgb(236, 236, 236);
    padding: 3px 3px 0px 0px;
}

/* unvisited link */
    a:link {
    color: rgb(0, 0, 0);
}

/* visited link */
    a:visited {
    color: rgb(0, 0, 0);
}

/* mouse over link */
    a:hover {
    color: rgb(128, 128, 128);
}

/* selected link */
    a:active {
    color: rgb(128, 128, 128);
}

a:link {
    text-decoration: none;
}

a:visited {
    text-decoration: none;
}

a:hover {
    text-decoration: none;
}

a:active {
    text-decoration: none;
}

td.color-white, div.color-white {
    border-color: rgb(255, 255, 255);
    border-left-width: 15px;
    background-color: white;
}

td.color-yellow, div.color-yellow {
    border-color: rgb(223, 227, 45);
    border-left-width: 15px;
    background-color: white;
}

td.color-blue, div.color-blue {
    border-color: rgb(10, 76, 153);
    border-left-width: 15px;
    background-color: white;
}

td.color-green, div.color-green {
    border-color: rgb(0, 153, 76);
    border-left-width: 15px;
    background-color: white;
}

td.color-purple, div.color-purple {
    border-color: rgb(51, 0, 102);
    border-left-width: 15px;
   background-color: white;
}

td.color-red, div.color-red {
    border-color: rgb(153, 0, 0);
    border-left-width: 15px;
    background-color: white;
}

td.color-orange, div.color-orange {
    border-color: rgb(204, 102, 0);
    border-left-width: 15px;
    background-color: white;
}

td.color-grey, div.color-grey {
    border-color: rgb(204, 204, 204);
    border-left-width: 15px;
    background-color: white;
}
```
