### ISSUE TITLE
[Feature request] Hightlight subtask table rows on mouse over

### ISSUE THREAD

**Issue by orlov0562** [fguillot/kanboard#1794]
Hi there,

I faced with order sorting of 50+ subtasks, and it very uncomfortable to locate needed menu icon of subtask to move it up/down. So I suggest to add very simple css that highlight table row when mouse on it:
```css
.subtasks-table tr:hover td {background-color:#F5F7C4; border-bottom:1px solid #dfe32d;}
```
