### ISSUE TITLE
Tooltip Improvement

### ISSUE THREAD

**Issue by ameeriqbal** [fguillot/kanboard#450]
Hi

Someone please take a look on this too.. http://www.tippedjs.com/ . I feel like need for a better skin also.

**Comment by jacob418** [comment]
I went to "*<MyKanboardPath>/app/Template/*".
There was a file named "*layout.php*". In the editor i addet this line
```html
<link rel="stylesheet" type="text/css" href="assets/css/custom.css">
```
at line 18 right after
```php
<?= $this->css('assets/css/app.css') ?>
```
Afterwards i created a new file via ftp at "*<MyKanboardPath>/assets/css/*" named "*custom.css*".
###### custom.css
```css
#popover-container #popover-content{
	overflow: auto;
	max-width: 870px;
}
.sidebar li{
	margin: 2px 0 ;
	list-style: none ;
}
.sidebar ul a{
	display: block;
	background: #dddde6 ;
	padding: 1px 15px ;
	border-radius: 2px ;
	text-decoration: none ;
	color: #333 ;
	border: 1px solid #dddde6 ;
	box-shadow: inset 0 0 5px 0 #dddde6 ;
}
.sidebar ul a:hover{
	background: #eee ;
	color: #666 ;
}
.sidebar ul a:active{
	background: #fff ;
	color: #666 ;
}
a{
	color: #002288;
}
```
This css-file also alters the apperance of hyperlinks, that where left blue and the menu in the sidebar.  The Menu now looks more like a menue und the Blue of the hyperlinks is not that light anymore. Feel free to abuse anything of that.
Maybe devs are adding a custom css by default. That would be great!
