### ISSUE TITLE
[Bug] Custom CSS special characters

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#723]
I was playing around with the new custom css feature #666 , it is very nice, but there is a problem with some special characters.

Example in settings:

```CSS
div[data-category-id = "1"] {
    background-color: red;
}
```

It will be included as:
```CSS
div[data-category-id = &quot;1&quot;] {
 background-color: red;
}
```

And so it is no valid Css and doesn't work.
